name: Release Extension
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
      WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
      CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
      CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: "Base Extension"
        run: npm ci

      - name: Get Version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build Chrome and Firefox Extensions
        working-directory: "Base Extension"
        run: node scripts/build.mjs
        env:
          NEW_VERSION: ${{ env.VERSION }}

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Lint Firefox Extension
        working-directory: "Base Extension/build/firefox"
        run: web-ext lint

      - name: Create Zip and XPI Archives
        working-directory: "Base Extension/build"
        run: |
          cd chrome
          zip -r ../../chrome-extension-${{ env.VERSION }}.zip *
          cd ../firefox
          zip -r ../../firefox-extension-${{ env.VERSION }}.xpi *

      - name: Upload Chrome Extension to GitHub Release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: chrome-extension-${{ env.VERSION }}.zip
          path: Base Extension/chrome-extension-${{ env.VERSION }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Firefox Extension to GitHub Release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: firefox-extension-${{ env.VERSION }}.xpi
          path: Base Extension/firefox-extension-${{ env.VERSION }}.xpi
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload and Publish to Mozilla Firefox Store
        # Only runs if API keys are set AND the GitHub release is NOT marked as a "Pre-release" (Beta).
        if: ${{ env.WEB_EXT_API_KEY != '' && env.WEB_EXT_API_SECRET != '' && github.event.release.prerelease == false }}
        working-directory: "Base Extension"
        run: web-ext sign --source-dir ./build/firefox --channel listed
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}

      - name: Upload and Publish to Chrome Web Store
        # Only runs if API credentials are set AND the GitHub release is NOT marked as a "Pre-release" (Beta).
        if: ${{ env.CHROME_CLIENT_ID != '' && env.CHROME_CLIENT_SECRET != '' && env.CHROME_REFRESH_TOKEN != '' && env.CHROME_EXTENSION_ID != '' && github.event.release.prerelease == false }}
        uses: mnao305/chrome-extension-upload@v6.0.0
        with:
          file-path: "Base Extension/chrome-extension-${{ env.VERSION }}.zip"
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: true

